### ISSUE TITLE
User friendly filtering

### ISSUE THREAD

**Issue by kowshikn** [opendistro-for-elasticsearch/trace-analytics#15]
Right now the filtering is directly based on on the field names in the index. Can this be made user friendly, example `durationInNanos` is not user friendly. If this can be changed as `latency (in ms)` and the at the query layer convert to nanos and apply it in filter. 

Also, the filter only supports `is, in between and not in between, equal to operation` can we support less than, greater than instead?
<img width="743" alt="Screen Shot 2021-01-29 at 3 17 20 PM" src="https://user-images.githubusercontent.com/57502753/106328247-19337400-6245-11eb-8f98-8e98f65a4c23.png">

**Comment by joshuali925** [comment]
This behavior is similar to Kibana Discover. If you leave one side blank in `in between`, it will become negative infinity or positive infinity, which is same as less than or greater than

**Comment by kowshikn** [comment]
I understand that its based on kibana, thats why called it as a new enhancement. I don't think this filtering is customer friendly, we should think of ways to make this easy.

**Comment by joshuali925** [comment]
merged into issue in opensearch repo https://github.com/opensearch-project/trace-analytics/issues/17, closing this
