### ISSUE TITLE
Variance 

### ISSUE THREAD

**Issue by kowshikn** [opendistro-for-elasticsearch/trace-analytics#16]
<img width="743" alt="Screen Shot 2021-01-29 at 3 21 45 PM" src="https://user-images.githubusercontent.com/57502753/106328598-b5f61180-6245-11eb-8d8c-7478def60d95.png">

I applied a filter by duration, shouldn't the latency variance change based on the filter?

**Comment by joshuali925** [comment]
That would be inconsistent if we apply <95 percentile filter. Our last decision was that the latency variance plot should not be affected by filters

**Comment by kowshikn** [comment]
We should have discussion on this. The problem is 24hour trend applies the filter but variance and percentile doesn't. This could be confusing to users.

**Comment by joshuali925** [comment]
This needs more discussion in term of user experience. We'll move the discussion to opensearch repo https://github.com/opensearch-project/trace-analytics/issues/17, closing it here
