### ISSUE TITLE
24 hour trend

### ISSUE THREAD

**Issue by kowshikn** [opendistro-for-elasticsearch/trace-analytics#17]
<img width="1559" alt="Screen Shot 2021-01-29 at 3 24 17 PM" src="https://user-images.githubusercontent.com/57502753/106328912-33218680-6246-11eb-8f40-c3ad207b0cd9.png">

The 24 hour trend line never matches with zoom. I agree the dataset I used us actually is almost constant so the hour average in the zoom is correct, but why the trend is not matching.

**Comment by joshuali925** [comment]
This happened because Plotly used inconsistent lower bounds for y-axis (0 vs the minimum latency) so scale is off. Should be fixed now by forcing minimum y range to be 0 on both plots
![image](https://user-images.githubusercontent.com/28062824/106342758-01fd8200-6257-11eb-900b-db064619d48e.png)
