### ISSUE TITLE
TraceGroup filtering updates

### ISSUE THREAD

**Issue by wrijeff** [opendistro-for-elasticsearch/trace-analytics#27]
Issue tracking query updates necessary to support traceGroup filtering.

Planning on populating the "traceGroup" field for every document, we'll need to adjust the queries to use "parentSpanId" to identify the trace group span.

**Comment by wrijeff** [comment]
We're planning on adding the following to each span:

- traceGroup.durationInNanos
- traceGroup.endTime
- traceGroup.status.code 
- traceGroup.name

The original "traceGroup" string field will be replaced by a nested field.

@joshuali925 @chenqi0805 @kowshikn let me know if you think anything needs to be changed.

**Comment by joshuali925** [comment]
After this change, dashboard average latency column will be calculated by `avg(traceGroup.duration for all traces)`. But the docs that goes into the aggregation are all spans.

For example, after filtering by `service=payment`, we see 10 spans with `trace-id-A`, each gets populated with `traceGroup.duration = 20`, and 1 span with `trace-id-B`, its duration is 100. (Let's assume all parent spans are of a different service, so none of them are parent spans)

The correct average latency should be `(20 + 100) / 2`, but using `avg` it becomes `(20 * 10 + 100) / 2`. I don’t see a straight forward way to do this in DSL (although might be possible with painless script), before you make the change do you see anything that can be done in the backend to help this? @wrijeff FYI @kowshikn

**Comment by wrijeff** [comment]
Would [collapse](https://www.elastic.co/guide/en/elasticsearch/reference/current/collapse-search-results.html) help here? I'm not sure if it can be used with aggregations though.

**Comment by joshuali925** [comment]
> Would [collapse](https://www.elastic.co/guide/en/elasticsearch/reference/current/collapse-search-results.html) help here? I'm not sure if it can be used with aggregations though.

Collapse is for hits (actual documents), doesn't seem to affect aggregations.
Using sample data to test: the query returns 2 docs in `hits` rather than 4, but `avg` duration aggregation is still 175.
```
GET ta-test/_search
{
  "size": 100, 
  "aggs": {
    "average": {
      "avg": {
        "field": "traceGroup.durationInNanos"
      }
    }
  },
  "collapse": {
    "field": "traceId.keyword"
  }
}
```

**Comment by wrijeff** [comment]
Thanks @joshuali925 for testing. Another possible approach might be to break the query up into multiple requests: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html#_filtering_values_with_partitions.

Also see [top_hits](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-top-hits-aggregation.html) for a way to sample just 1 result per bucket instead of having to divide the by count in the query.

Though with any of these approaches, we need to know how scalable they are and at what point will the queries break (e.g. 1 million unique traces, 100 million spans, etc.)

**Comment by joshuali925** [comment]
Thanks, we'll go with `terms` aggs for now with a size limit. As for `top_hits` we can just use `max` or `min` since they are all the same.

I was thinking would it be a better approach to put all services used in the trace in the parent span (e.g. `{ traceServices: [payment, order], parentSpanId: "", service: order }`) rather than denormalization? 

This way when filtering by service, I can just filter out the parent spans and filter within the `traceServices` field. Although I'm not very familiar with data prepper/backend, not sure if it's possible or would introduce other problems. @wrijeff

**Comment by wrijeff** [comment]
Update on this issue - previously Data Prepper planned to go with the collection `traceGroup.*` approach, however due to compatibility issues we ultimately went back to `traceGroupFields`. Here is a link to the [1.0.x schema template](https://github.com/opendistro-for-elasticsearch/data-prepper/blob/v1.0.x/data-prepper-plugins/elasticsearch/src/main/resources/otel-v1-apm-span-index-template.json#L42-L58) going forward. I have an item to make these schemas more discoverable in a docs location.

We'll need to commit one last revert to go back to `traceGroupFields` in this and the OpenSearch repos to get everything realigned.  @joshuali925 please let me know if you have bandwidth, if not I can open the revert PRs.

**Comment by joshuali925** [comment]
@wrijeff which commit is it? I'm seeing `traceGroupFields.name` in this commit but `traceGroup` in the schema, am I looking at the wrong commit?

https://github.com/opendistro-for-elasticsearch/trace-analytics/commit/0c09b5fa3c44ef0957884b0ec3cd1cf6e216ef5d#diff-e0a9091557e3b1a397323fd897f6a02dc1288920317c06f4fd483571c3ea2254R77

**Comment by wrijeff** [comment]
I believe it's https://github.com/opendistro-for-elasticsearch/trace-analytics/commit/c84ecb4f3d429e75d923a54dbcf8462642b5402c that needs to be reverted. This should get us back to `traceGroup` being a string name, and `traceGroupFields` containing the other 3 fields.

**Comment by joshuali925** [comment]
Got it, opened PR #39, I'll do some tests before merging it

**Comment by wrijeff** [comment]
Thanks @joshuali925, I think this one can be closed now. We'll be synchronizing ODFE and OS Data Prepper to use the same schema - could you apply https://github.com/opendistro-for-elasticsearch/trace-analytics/pull/39 to the OpenSearch repo too?

**Comment by joshuali925** [comment]
Thanks, rebase PR is open in OpenSearch repo, closing issue now
