### ISSUE TITLE
Check for null values when processing service map

### ISSUE THREAD

**Issue by wrijeff** [opendistro-for-elasticsearch/trace-analytics#32]
Related to https://github.com/opendistro-for-elasticsearch/data-prepper/issues/479.

There is an issue that causes the list on the Services page to disappear if a record in the underlying service-map index is missing. We still don't know the exact cause on the ingestion side, but please add null checks to handle this case if part of a destination-target pair of records is missing. 

Will attempt to increase resiliency in Data Prepper either through retries or by periodically re-sending service map records.

**Comment by joshuali925** [comment]
Fix is merged to ignore partial records, closing issue
