### ISSUE TITLE
Filter by Attributes

### ISSUE THREAD

**Issue by kowshikn** [opendistro-for-elasticsearch/trace-analytics#36]
also, it will be good to have an ability to filter by attributes. for example we have traces from different regions in the same Elasticsearch cluster and we have below attributes for every trace:

  "span.attributes.internal@span@format": "zipkin",
  "span.attributes.hostname": "test-service-c5867c747-7flkj",
  "span.attributes.cluster": "k8s-test-us-east-1",
  "resource.attributes.env": "DEV",
  "span.attributes.region": "us-east-1",
  "resource.attributes.service@name": "test-service",
  
 Note: From [Opendistro community.](https://discuss.opendistrocommunity.dev/t/find-traces-by-service/5704)

**Comment by joshuali925** [comment]
opened issue in opensearch repo https://github.com/opensearch-project/trace-analytics/issues/15, closing this
