### ISSUE TITLE
Can´t see Traces

### ISSUE THREAD

**Issue by santunioni** [opendistro-for-elasticsearch/trace-analytics#50]
Good afternoon.

As you can see in the print, my Data-Prepper + ElasticSearch (open distro) + Kibana in AWS setup shows I am receiving OTEL data (look at Traces over time). However, I can´t see any trace or service-map. It worked fine in localhost, with docker-compose.     

- [x] I already checked I am receiving data with the query `GET otel-v1-apm-*/_search`.   

Have any of you encountered this problem before?

![Screenshot from 2021-10-04 15-00-06](https://user-images.githubusercontent.com/60983144/135901558-fb68d6b0-2b3b-4693-8904-583e1d45de6a.png)

**Comment by joshuali925** [comment]
Hi @santunioni thanks for filling out an issue. Which ES/Kibana version are you on? And do you see any errors under developer tools console or network tab?

**Comment by santunioni** [comment]
Hi, @joshuali925. Sorry for the delay to answer. The versions were 7.10 for ES and Kibana. I didn't see any errors under developer tools. 
However, my team upgraded to OpenSearch+Dashboards and we can now use the plugin perfectly. 
Sorry if I can't answer more questions about the possible bug, because I no longer have access to the version 7.10.
